apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-pod
  name: nginx-pod-new
spec:
  containers:
  - image: nginx
    name: nginx-pod-new
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}