apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-04-10T10:45:34Z"
  labels:
    run: nginx
    tier: frontend
    type: app1
  name: nginx
  namespace: default
  resourceVersion: "80928"
  uid: 77af6625-23af-4a55-9aef-6b898e826419
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
  nodeName: cka-cluster3-worker